# Generated by Django 4.0.3 on 2022-03-19 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location_neighbourhood_post_contact_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='neigbourhood',
        ),
        migrations.AddField(
            model_name='user',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhoods', to=settings.AUTH_USER_MODEL),
        ),
    ]
